USE website;

CREATE TABLE IF NOT EXISTS customers (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    bill_fname VARCHAR(50),
    bill_lname VARCHAR(50),
    phone      VARCHAR(15),
    email      VARCHAR(128),
    address    VARCHAR(255),
    cdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS employees (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    username  VARCHAR(25) NOT NULL,
    full_name VARCHAR(128) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    status    ENUM('employee', 'manager', 'disabled') NOT NULL DEFAULT 'employee',
    UNIQUE INDEX (username),
    cdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    customer_id INT UNSIGNED NOT NULL,
    order_date  DATETIME NOT NULL,
    total_price DECIMAL(6,2) NOT NULL,
    status      VARCHAR(25) DEFAULT 'Pending' NOT NULL,
    comments    TEXT,
    FOREIGN KEY (customer_id) REFERENCES customers (id),
    cdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS order_details (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    order_id INT UNSIGNED NOT NULL,
    item_name      VARCHAR(128) NOT NULL,
    size           VARCHAR(128) NOT NULL,
    toppings       VARCHAR(128),
    quantity       INT UNSIGNED NOT NULL,
    price_per_unit DECIMAL(6,2) NOT NULL,
    topping_price  DECIMAL(6,2) NOT NULL,
    FOREIGN KEY (order_id) REFERENCES orders (id),
    cdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    mdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);